set_property SRC_FILE_INFO {cfile:G:/FPGA_ZYNQ_IC_Learn/IC/riscv/riscv32_order_pipeline/riscv_zicsrim_cpu/fpga/led.srcs/constrs_1/new/led.xdc rfile:../../../led.srcs/constrs_1/new/led.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15 [get_ports sys_rst_n]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18 [get_ports sys_clk]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G14 [get_ports led]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y7 [get_ports uart_tx]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y6 [get_ports uart_rx]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V20 [get_ports debug_en]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list u_clk_rst_gen/inst/clk_out1]]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {u_top/u_uart/tx_data[0]} {u_top/u_uart/tx_data[1]} {u_top/u_uart/tx_data[2]} {u_top/u_uart/tx_data[3]} {u_top/u_uart/tx_data[4]} {u_top/u_uart/tx_data[5]} {u_top/u_uart/tx_data[6]} {u_top/u_uart/tx_data[7]}]]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {u_top/u_uart/uart_baud[0]} {u_top/u_uart/uart_baud[1]} {u_top/u_uart/uart_baud[2]} {u_top/u_uart/uart_baud[3]} {u_top/u_uart/uart_baud[4]} {u_top/u_uart/uart_baud[5]} {u_top/u_uart/uart_baud[6]} {u_top/u_uart/uart_baud[7]} {u_top/u_uart/uart_baud[8]} {u_top/u_uart/uart_baud[9]} {u_top/u_uart/uart_baud[10]} {u_top/u_uart/uart_baud[11]} {u_top/u_uart/uart_baud[12]} {u_top/u_uart/uart_baud[13]} {u_top/u_uart/uart_baud[14]} {u_top/u_uart/uart_baud[15]} {u_top/u_uart/uart_baud[16]} {u_top/u_uart/uart_baud[17]} {u_top/u_uart/uart_baud[18]} {u_top/u_uart/uart_baud[19]} {u_top/u_uart/uart_baud[20]} {u_top/u_uart/uart_baud[21]} {u_top/u_uart/uart_baud[22]} {u_top/u_uart/uart_baud[23]} {u_top/u_uart/uart_baud[24]} {u_top/u_uart/uart_baud[25]} {u_top/u_uart/uart_baud[26]} {u_top/u_uart/uart_baud[27]} {u_top/u_uart/uart_baud[28]} {u_top/u_uart/uart_baud[29]} {u_top/u_uart/uart_baud[30]} {u_top/u_uart/uart_baud[31]}]]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {u_top/u_uart/state[0]} {u_top/u_uart/state[1]} {u_top/u_uart/state[2]} {u_top/u_uart/state[3]}]]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {u_top/u_uart/uart_rx[0]} {u_top/u_uart/uart_rx[1]} {u_top/u_uart/uart_rx[2]} {u_top/u_uart/uart_rx[3]} {u_top/u_uart/uart_rx[4]} {u_top/u_uart/uart_rx[5]} {u_top/u_uart/uart_rx[6]} {u_top/u_uart/uart_rx[7]} {u_top/u_uart/uart_rx[8]} {u_top/u_uart/uart_rx[9]} {u_top/u_uart/uart_rx[10]} {u_top/u_uart/uart_rx[11]} {u_top/u_uart/uart_rx[12]} {u_top/u_uart/uart_rx[13]} {u_top/u_uart/uart_rx[14]} {u_top/u_uart/uart_rx[15]} {u_top/u_uart/uart_rx[16]} {u_top/u_uart/uart_rx[17]} {u_top/u_uart/uart_rx[18]} {u_top/u_uart/uart_rx[19]} {u_top/u_uart/uart_rx[20]} {u_top/u_uart/uart_rx[21]} {u_top/u_uart/uart_rx[22]} {u_top/u_uart/uart_rx[23]} {u_top/u_uart/uart_rx[24]} {u_top/u_uart/uart_rx[25]} {u_top/u_uart/uart_rx[26]} {u_top/u_uart/uart_rx[27]} {u_top/u_uart/uart_rx[28]} {u_top/u_uart/uart_rx[29]} {u_top/u_uart/uart_rx[30]} {u_top/u_uart/uart_rx[31]}]]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {u_top/u_uart/rx_clk_edge_cnt[0]} {u_top/u_uart/rx_clk_edge_cnt[1]} {u_top/u_uart/rx_clk_edge_cnt[2]} {u_top/u_uart/rx_clk_edge_cnt[3]}]]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {u_top/u_uart/uart_ctrl[0]} {u_top/u_uart/uart_ctrl[1]} {u_top/u_uart/uart_ctrl[2]} {u_top/u_uart/uart_ctrl[3]} {u_top/u_uart/uart_ctrl[4]} {u_top/u_uart/uart_ctrl[5]} {u_top/u_uart/uart_ctrl[6]} {u_top/u_uart/uart_ctrl[7]} {u_top/u_uart/uart_ctrl[8]} {u_top/u_uart/uart_ctrl[9]} {u_top/u_uart/uart_ctrl[10]} {u_top/u_uart/uart_ctrl[11]} {u_top/u_uart/uart_ctrl[12]} {u_top/u_uart/uart_ctrl[13]} {u_top/u_uart/uart_ctrl[14]} {u_top/u_uart/uart_ctrl[15]} {u_top/u_uart/uart_ctrl[16]} {u_top/u_uart/uart_ctrl[17]} {u_top/u_uart/uart_ctrl[18]} {u_top/u_uart/uart_ctrl[19]} {u_top/u_uart/uart_ctrl[20]} {u_top/u_uart/uart_ctrl[21]} {u_top/u_uart/uart_ctrl[22]} {u_top/u_uart/uart_ctrl[23]} {u_top/u_uart/uart_ctrl[24]} {u_top/u_uart/uart_ctrl[25]} {u_top/u_uart/uart_ctrl[26]} {u_top/u_uart/uart_ctrl[27]} {u_top/u_uart/uart_ctrl[28]} {u_top/u_uart/uart_ctrl[29]} {u_top/u_uart/uart_ctrl[30]} {u_top/u_uart/uart_ctrl[31]}]]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {u_top/u_uart/uart_status[0]} {u_top/u_uart/uart_status[1]} {u_top/u_uart/uart_status[2]} {u_top/u_uart/uart_status[3]} {u_top/u_uart/uart_status[4]} {u_top/u_uart/uart_status[5]} {u_top/u_uart/uart_status[6]} {u_top/u_uart/uart_status[7]} {u_top/u_uart/uart_status[8]} {u_top/u_uart/uart_status[9]} {u_top/u_uart/uart_status[10]} {u_top/u_uart/uart_status[11]} {u_top/u_uart/uart_status[12]} {u_top/u_uart/uart_status[13]} {u_top/u_uart/uart_status[14]} {u_top/u_uart/uart_status[15]} {u_top/u_uart/uart_status[16]} {u_top/u_uart/uart_status[17]} {u_top/u_uart/uart_status[18]} {u_top/u_uart/uart_status[19]} {u_top/u_uart/uart_status[20]} {u_top/u_uart/uart_status[21]} {u_top/u_uart/uart_status[22]} {u_top/u_uart/uart_status[23]} {u_top/u_uart/uart_status[24]} {u_top/u_uart/uart_status[25]} {u_top/u_uart/uart_status[26]} {u_top/u_uart/uart_status[27]} {u_top/u_uart/uart_status[28]} {u_top/u_uart/uart_status[29]} {u_top/u_uart/uart_status[30]} {u_top/u_uart/uart_status[31]}]]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {u_top/u_uart/rx_data[0]} {u_top/u_uart/rx_data[1]} {u_top/u_uart/rx_data[2]} {u_top/u_uart/rx_data[3]} {u_top/u_uart/rx_data[4]} {u_top/u_uart/rx_data[5]} {u_top/u_uart/rx_data[6]} {u_top/u_uart/rx_data[7]}]]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list {u_top/u_uart_debug/mem_addr_o[0]} {u_top/u_uart_debug/mem_addr_o[1]} {u_top/u_uart_debug/mem_addr_o[2]} {u_top/u_uart_debug/mem_addr_o[3]} {u_top/u_uart_debug/mem_addr_o[4]} {u_top/u_uart_debug/mem_addr_o[5]} {u_top/u_uart_debug/mem_addr_o[6]} {u_top/u_uart_debug/mem_addr_o[7]} {u_top/u_uart_debug/mem_addr_o[8]} {u_top/u_uart_debug/mem_addr_o[9]} {u_top/u_uart_debug/mem_addr_o[10]} {u_top/u_uart_debug/mem_addr_o[11]} {u_top/u_uart_debug/mem_addr_o[12]} {u_top/u_uart_debug/mem_addr_o[13]} {u_top/u_uart_debug/mem_addr_o[14]} {u_top/u_uart_debug/mem_addr_o[15]} {u_top/u_uart_debug/mem_addr_o[16]} {u_top/u_uart_debug/mem_addr_o[17]} {u_top/u_uart_debug/mem_addr_o[18]} {u_top/u_uart_debug/mem_addr_o[19]} {u_top/u_uart_debug/mem_addr_o[20]} {u_top/u_uart_debug/mem_addr_o[21]} {u_top/u_uart_debug/mem_addr_o[22]} {u_top/u_uart_debug/mem_addr_o[23]} {u_top/u_uart_debug/mem_addr_o[24]} {u_top/u_uart_debug/mem_addr_o[25]} {u_top/u_uart_debug/mem_addr_o[26]} {u_top/u_uart_debug/mem_addr_o[27]} {u_top/u_uart_debug/mem_addr_o[28]} {u_top/u_uart_debug/mem_addr_o[29]} {u_top/u_uart_debug/mem_addr_o[30]} {u_top/u_uart_debug/mem_addr_o[31]}]]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list {u_top/u_uart_debug/mem_wdata_o[0]} {u_top/u_uart_debug/mem_wdata_o[1]} {u_top/u_uart_debug/mem_wdata_o[2]} {u_top/u_uart_debug/mem_wdata_o[3]} {u_top/u_uart_debug/mem_wdata_o[4]} {u_top/u_uart_debug/mem_wdata_o[5]} {u_top/u_uart_debug/mem_wdata_o[6]} {u_top/u_uart_debug/mem_wdata_o[7]} {u_top/u_uart_debug/mem_wdata_o[8]} {u_top/u_uart_debug/mem_wdata_o[9]} {u_top/u_uart_debug/mem_wdata_o[10]} {u_top/u_uart_debug/mem_wdata_o[11]} {u_top/u_uart_debug/mem_wdata_o[12]} {u_top/u_uart_debug/mem_wdata_o[13]} {u_top/u_uart_debug/mem_wdata_o[14]} {u_top/u_uart_debug/mem_wdata_o[15]} {u_top/u_uart_debug/mem_wdata_o[16]} {u_top/u_uart_debug/mem_wdata_o[17]} {u_top/u_uart_debug/mem_wdata_o[18]} {u_top/u_uart_debug/mem_wdata_o[19]} {u_top/u_uart_debug/mem_wdata_o[20]} {u_top/u_uart_debug/mem_wdata_o[21]} {u_top/u_uart_debug/mem_wdata_o[22]} {u_top/u_uart_debug/mem_wdata_o[23]} {u_top/u_uart_debug/mem_wdata_o[24]} {u_top/u_uart_debug/mem_wdata_o[25]} {u_top/u_uart_debug/mem_wdata_o[26]} {u_top/u_uart_debug/mem_wdata_o[27]} {u_top/u_uart_debug/mem_wdata_o[28]} {u_top/u_uart_debug/mem_wdata_o[29]} {u_top/u_uart_debug/mem_wdata_o[30]} {u_top/u_uart_debug/mem_wdata_o[31]}]]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 14 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list {u_top/u_uart_debug/state[0]} {u_top/u_uart_debug/state[1]} {u_top/u_uart_debug/state[2]} {u_top/u_uart_debug/state[3]} {u_top/u_uart_debug/state[4]} {u_top/u_uart_debug/state[5]} {u_top/u_uart_debug/state[6]} {u_top/u_uart_debug/state[7]} {u_top/u_uart_debug/state[8]} {u_top/u_uart_debug/state[9]} {u_top/u_uart_debug/state[10]} {u_top/u_uart_debug/state[11]} {u_top/u_uart_debug/state[12]} {u_top/u_uart_debug/state[13]}]]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list {u_top/m0_addr[0]} {u_top/m0_addr[1]} {u_top/m0_addr[2]} {u_top/m0_addr[3]} {u_top/m0_addr[4]} {u_top/m0_addr[5]} {u_top/m0_addr[6]} {u_top/m0_addr[7]} {u_top/m0_addr[8]} {u_top/m0_addr[9]} {u_top/m0_addr[10]} {u_top/m0_addr[11]} {u_top/m0_addr[12]} {u_top/m0_addr[13]} {u_top/m0_addr[14]} {u_top/m0_addr[15]} {u_top/m0_addr[16]} {u_top/m0_addr[17]} {u_top/m0_addr[18]} {u_top/m0_addr[19]} {u_top/m0_addr[20]} {u_top/m0_addr[21]} {u_top/m0_addr[22]} {u_top/m0_addr[23]} {u_top/m0_addr[24]} {u_top/m0_addr[25]} {u_top/m0_addr[26]} {u_top/m0_addr[27]} {u_top/m0_addr[28]} {u_top/m0_addr[29]} {u_top/m0_addr[30]} {u_top/m0_addr[31]}]]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list {u_top/m0_rdata[0]} {u_top/m0_rdata[1]} {u_top/m0_rdata[2]} {u_top/m0_rdata[3]} {u_top/m0_rdata[4]} {u_top/m0_rdata[5]} {u_top/m0_rdata[6]} {u_top/m0_rdata[7]} {u_top/m0_rdata[8]} {u_top/m0_rdata[9]} {u_top/m0_rdata[10]} {u_top/m0_rdata[11]} {u_top/m0_rdata[12]} {u_top/m0_rdata[13]} {u_top/m0_rdata[14]} {u_top/m0_rdata[15]} {u_top/m0_rdata[16]} {u_top/m0_rdata[17]} {u_top/m0_rdata[18]} {u_top/m0_rdata[19]} {u_top/m0_rdata[20]} {u_top/m0_rdata[21]} {u_top/m0_rdata[22]} {u_top/m0_rdata[23]} {u_top/m0_rdata[24]} {u_top/m0_rdata[25]} {u_top/m0_rdata[26]} {u_top/m0_rdata[27]} {u_top/m0_rdata[28]} {u_top/m0_rdata[29]} {u_top/m0_rdata[30]} {u_top/m0_rdata[31]}]]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list {u_top/m1_addr[0]} {u_top/m1_addr[1]} {u_top/m1_addr[2]} {u_top/m1_addr[3]} {u_top/m1_addr[4]} {u_top/m1_addr[5]} {u_top/m1_addr[6]} {u_top/m1_addr[7]} {u_top/m1_addr[8]} {u_top/m1_addr[9]} {u_top/m1_addr[10]} {u_top/m1_addr[11]} {u_top/m1_addr[12]} {u_top/m1_addr[13]} {u_top/m1_addr[14]} {u_top/m1_addr[15]} {u_top/m1_addr[16]} {u_top/m1_addr[17]} {u_top/m1_addr[18]} {u_top/m1_addr[19]} {u_top/m1_addr[20]} {u_top/m1_addr[21]} {u_top/m1_addr[22]} {u_top/m1_addr[23]} {u_top/m1_addr[24]} {u_top/m1_addr[25]} {u_top/m1_addr[26]} {u_top/m1_addr[27]} {u_top/m1_addr[28]} {u_top/m1_addr[29]} {u_top/m1_addr[30]} {u_top/m1_addr[31]}]]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list {u_top/m1_size[0]} {u_top/m1_size[1]} {u_top/m1_size[2]}]]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe15 [get_nets [list {u_top/m1_rdata[0]} {u_top/m1_rdata[1]} {u_top/m1_rdata[2]} {u_top/m1_rdata[3]} {u_top/m1_rdata[4]} {u_top/m1_rdata[5]} {u_top/m1_rdata[6]} {u_top/m1_rdata[7]} {u_top/m1_rdata[8]} {u_top/m1_rdata[9]} {u_top/m1_rdata[10]} {u_top/m1_rdata[11]} {u_top/m1_rdata[12]} {u_top/m1_rdata[13]} {u_top/m1_rdata[14]} {u_top/m1_rdata[15]} {u_top/m1_rdata[16]} {u_top/m1_rdata[17]} {u_top/m1_rdata[18]} {u_top/m1_rdata[19]} {u_top/m1_rdata[20]} {u_top/m1_rdata[21]} {u_top/m1_rdata[22]} {u_top/m1_rdata[23]} {u_top/m1_rdata[24]} {u_top/m1_rdata[25]} {u_top/m1_rdata[26]} {u_top/m1_rdata[27]} {u_top/m1_rdata[28]} {u_top/m1_rdata[29]} {u_top/m1_rdata[30]} {u_top/m1_rdata[31]}]]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe16 [get_nets [list {u_top/m1_wdata[0]} {u_top/m1_wdata[1]} {u_top/m1_wdata[2]} {u_top/m1_wdata[3]} {u_top/m1_wdata[4]} {u_top/m1_wdata[5]} {u_top/m1_wdata[6]} {u_top/m1_wdata[7]} {u_top/m1_wdata[8]} {u_top/m1_wdata[9]} {u_top/m1_wdata[10]} {u_top/m1_wdata[11]} {u_top/m1_wdata[12]} {u_top/m1_wdata[13]} {u_top/m1_wdata[14]} {u_top/m1_wdata[15]} {u_top/m1_wdata[16]} {u_top/m1_wdata[17]} {u_top/m1_wdata[18]} {u_top/m1_wdata[19]} {u_top/m1_wdata[20]} {u_top/m1_wdata[21]} {u_top/m1_wdata[22]} {u_top/m1_wdata[23]} {u_top/m1_wdata[24]} {u_top/m1_wdata[25]} {u_top/m1_wdata[26]} {u_top/m1_wdata[27]} {u_top/m1_wdata[28]} {u_top/m1_wdata[29]} {u_top/m1_wdata[30]} {u_top/m1_wdata[31]}]]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe17 [get_nets [list {timer_cnt[0]} {timer_cnt[1]} {timer_cnt[2]} {timer_cnt[3]} {timer_cnt[4]} {timer_cnt[5]} {timer_cnt[6]} {timer_cnt[7]} {timer_cnt[8]} {timer_cnt[9]} {timer_cnt[10]} {timer_cnt[11]} {timer_cnt[12]} {timer_cnt[13]} {timer_cnt[14]} {timer_cnt[15]} {timer_cnt[16]} {timer_cnt[17]} {timer_cnt[18]} {timer_cnt[19]} {timer_cnt[20]} {timer_cnt[21]} {timer_cnt[22]} {timer_cnt[23]} {timer_cnt[24]} {timer_cnt[25]} {timer_cnt[26]} {timer_cnt[27]} {timer_cnt[28]} {timer_cnt[29]} {timer_cnt[30]} {timer_cnt[31]}]]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe18 [get_nets [list {debug_en_r[0]} {debug_en_r[1]} {debug_en_r[2]} {debug_en_r[3]} {debug_en_r[4]} {debug_en_r[5]} {debug_en_r[6]} {debug_en_r[7]}]]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe19 [get_nets [list debug_en_w]]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe20 [get_nets [list u_top/m1_rd]]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe21 [get_nets [list u_top/m1_we]]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe22 [get_nets [list u_top/u_uart_debug/mem_rd_o]]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe23 [get_nets [list u_top/u_uart_debug/mem_we_o]]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe24 [get_nets [list u_top/u_uart/rx_negedge]]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe25 [get_nets [list u_top/u_uart/rx_over]]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe26 [get_nets [list u_top/u_uart/rx_q0]]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe27]
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe27 [get_nets [list u_top/u_uart/rx_q1]]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe28]
set_property src_info {type:XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe28 [get_nets [list u_top/u_uart/rx_start]]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk]
